use serde::Deserialize;
use std::collections::HashMap;
use std::path::Path;

#[derive(Debug, Clone, Deserialize)]
pub struct HooksConfig {
    #[serde(default)]
    pub hooks: HashMap<String, HookDef>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct HookDef {
    pub command: String,
    #[serde(default = "default_hook_type")]
    pub hook_type: String,
    #[serde(default)]
    pub autostart: bool,
    #[serde(default)]
    pub platforms: Vec<String>,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub args: Vec<String>,
    #[serde(default)]
    pub env: HashMap<String, String>,
    #[serde(default = "default_timeout")]
    pub timeout_ms: u64,
}

fn default_hook_type() -> String {
    "service".to_string()
}

fn default_timeout() -> u64 {
    5000
}

impl HooksConfig {
    pub fn from_file(path: &Path) -> Result<Self, String> {
        let content = std::fs::read_to_string(path)
            .map_err(|e| format!("Failed to read hooks config: {}", e))?;
        if path.extension().map_or(false, |e| e == "json") {
            serde_json::from_str(&content)
                .map_err(|e| format!("Failed to parse hooks JSON: {}", e))
        } else {
            parse_toml_like(&content)
        }
    }

    pub fn active_on_platform(&self, platform: &str) -> Vec<(&str, &HookDef)> {
        self.hooks.iter()
            .filter(|(_, def)| {
                def.platforms.is_empty() || def.platforms.iter().any(|p| p == platform)
            })
            .map(|(name, def)| (name.as_str(), def))
            .collect()
    }

    pub fn generate_cpp_config(&self, platform: &str) -> String {
        let active = self.active_on_platform(platform);
        let mut cpp = String::from("// Auto-generated by bridge hooks parser\n");
        cpp.push_str("static const HookEntry g_hooks[] = {\n");
        for (name, def) in &active {
            cpp.push_str(&format!(
                "    {{ \"{}\", \"{}\", {}, {} }},\n",
                name.replace('\\', "\\\\").replace('"', "\\\""),
                def.command.replace('\\', "\\\\").replace('"', "\\\""),
                if def.autostart { "true" } else { "false" },
                def.timeout_ms,
            ));
        }
        cpp.push_str("};\n");
        cpp.push_str(&format!("static const int g_hookCount = {};\n", active.len()));
        cpp
    }
}

fn parse_toml_like(content: &str) -> Result<HooksConfig, String> {
    let mut hooks = HashMap::new();
    let mut current_section: Option<String> = None;
    let mut current_def: Option<HookDef> = None;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') || trimmed.starts_with("//") {
            continue;
        }

        if trimmed.starts_with('[') && trimmed.ends_with(']') {
            if let Some(name) = current_section.take() {
                if let Some(def) = current_def.take() {
                    hooks.insert(name, def);
                }
            }
            let section = &trimmed[1..trimmed.len() - 1];
            if let Some(hook_name) = section.strip_prefix("hooks.") {
                current_section = Some(hook_name.to_string());
                current_def = Some(HookDef {
                    command: String::new(),
                    hook_type: default_hook_type(),
                    autostart: false,
                    platforms: Vec::new(),
                    description: String::new(),
                    args: Vec::new(),
                    env: HashMap::new(),
                    timeout_ms: default_timeout(),
                });
            }
            continue;
        }

        if let (Some(name), Some(ref mut def)) = (&current_section, &mut current_def) {
            if let Some(eq_pos) = trimmed.find('=') {
                let key = trimmed[..eq_pos].trim();
                let value = trimmed[eq_pos + 1..].trim();
                let val = value.trim_matches('"');
                match key {
                    "command" => def.command = val.to_string(),
                    "type" => def.hook_type = val.to_string(),
                    "autostart" => def.autostart = val == "true",
                    "description" => def.description = val.to_string(),
                    "timeout_ms" => def.timeout_ms = val.parse().unwrap_or(default_timeout()),
                    "platforms" => {
                        def.platforms = val.trim_start_matches('[').trim_end_matches(']')
                            .split(',').map(|s| s.trim().trim_matches('"').to_string())
                            .filter(|s| !s.is_empty()).collect();
                    }
                    _ => {}
                }
            }
        }
    }

    if let Some(name) = current_section {
        if let Some(def) = current_def {
            hooks.insert(name, def);
        }
    }

    Ok(HooksConfig { hooks })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_toml_like() {
        let input = r#"
[hooks.notify]
command = "fdf-notify"
type = "service"
autostart = true
platforms = ["linux", "macos"]
description = "Notification daemon"
timeout_ms = 3000

[hooks.calendar]
command = "fdf-calendar"
type = "oneshot"
autostart = false
"#;
        let config = parse_toml_like(input).unwrap();
        assert_eq!(config.hooks.len(), 2);
        assert!(config.hooks.contains_key("notify"));
        assert!(config.hooks.contains_key("calendar"));
        assert_eq!(config.hooks["notify"].command, "fdf-notify");
        assert_eq!(config.hooks["notify"].hook_type, "service");
        assert!(config.hooks["notify"].autostart);
        assert_eq!(config.hooks["calendar"].hook_type, "oneshot");
        assert!(!config.hooks["calendar"].autostart);
    }
}
